project:
  type: website
  output-dir: docs

website:
  title: "Curso Introdução ao R e Tidyverse"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Material"
        menu:
          - text: "Aula 01: Introdução ao R"
            href: material/aula01-introducao-r.qmd
          - text: "Aula 02: Importar Dados"
            href: material/aula02-importar.qmd
          - text: "Aula 03: Arrumar Dados"
            href: material/aula03-arrumar.qmd
          - text: "Aula 04: Transformar Dados"
            href: material/aula04-transformar.qmd
          - text: "Aula 05: Visualizar Dados"
            href: material/aula05-visualizar.qmd
          - text: "Aula 06: Visualizar Dados - Avançado"
            href: material/aula06-visualizar_avancado.qmd
          - text: "Aula 07: Visualizar Dados - Interseções"
            href: material/aula07-visualizar_intersecoes.qmd
      - text: "Desafio"
        menu:
          - text: "Desafio 01: Barplot de expressão"
            href: material/desafio01-barplot_expressao.qmd
          - text: "Desafio 02: Boxplot do expressão em cancer"
            href: material/desafio02-boxplot_expressao_cancer.qmd
          - text: "Desafio 03: Heatmap de expressão de oncogenes"
            href: material/desafio03-heatmap.qmd
          - text: "Desafio 04: Top genes compartilhados"
            href: material/desafio04-top_compartilhados.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
